services:
  nextjs-app:
    build: .
    ports:
      - "3000:3000"
      - "25565:25565"
      - "25575:25575"
    environment:
      NODE_ENV: production
    volumes:
      - ./data:/app/data
      - ./servers:/app/servers